"""
Django settings for deployPortal project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't0ksv*7!cc5((27k^_3c%d0427@%#t+=20iza8+x1p+5d471^)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


TEMPLATES_DIR = '%s/templates' % BASE_DIR

# Additional locations of static files
STATICFILES_DIRS = (
    '%s/static-assets' % BASE_DIR,
)



# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_deployment',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deployPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deployPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

#MURANO_APP related settings

MURANO_CONNECT = {
        'ip': 'tacker-mitaka-y8uyph4a.srv.ravcloud.com',
        'tenantname':'admin',
        'username':'admin',
        'password':'demo',
        'admin_token':'demo', 
        'env_name_prefix':'env_',
        
    }

MURANO_PACKAGE_REPO_URL = 'http://storage.apps.openstack.org/'

MURANO_PACKAGE_NAMES = {
    
        'apachehttpserver' :'io.murano.apps.apache.ApacheHttpServer',
        'apachetomcat' :'io.murano.apps.apache.Tomcat',
        #'dockerapp':'io.murano.apps.docker.DockerApp',
        'dockerapp':'io.murano.apps.docker.DockerStandaloneHost',
        'mysql' : 'io.murano.databases.MySql',
        'kubernetescluster' : 'io.murano.apps.docker.kubernetes.KubernetesCluster',
        'postgresql':'io.murano.databases.PostgreSql',
        'wordpess':'io.murano.apps.WordPress',
        'stackatonode':'io.murano.apps.activestate.StackatoNode',       
                        
                        
    }

MURANO_KEY_PAIR_NAME = 'cloud'

MURANO_CUSTOM_PACKAGE_DIR = '/home/rdk/PycharmProjects/iManage/static-assets/murano_packages'

UPLOAD_FILE_PATH = '/home/rdk/files'


MURANO_DAFAULT_IMAGE = 'ubuntu14.04-x64-murano'

